---
title: "Resume"
format: html
---
layout: resume
title: Jasper Naripogu's Resume
---


<div id="webaddress">
<a href="Jasperjoshi@byui.edu">Jasperjoshi@byui.edu</a>
| <a href="https://byuidatascience.github.io/development.html">Data Science Program</a>
</div>

<!-- https://www.monique.tech/the-art-of-markdown -->


## Education

`2008-2018`
__Delhi Public School__, Vijaywada, AP, India

- Full academic scholarship with 4.0 GPA

`Expected 2024`
__Brigham Young University - Idaho__, Rexburg, ID

- 3.4 Major GPA


## Skills
Communication 
Python 
Java                
MS Excel & MS Word
Discipline
Hard Working Capability
Customer Service 
Facebook ads
Instagram Targeting Advertising   
Google Shopping Insights 
Google Trends

                              


### Work Experience

`January 2028 - June 2028`
__Pacific Northwest National Lab__, Richland, WA

- Worked on novel methods for soil sampling to reduce laboratory measurements
- Used R and Visual Sample Plan to establish new sampling algorithms
- Published a journal article in Environmental Quality.


`April 2027 - June 2027`
__Westmark Credit Union__, Consultant

- Developed a predicted model to support Westmark in custumer conversion from dealer loans.
- Used R and Python to build a machine learning model using CatBoost in Python and the Tidyverse for data visualization and munging. 
- Improved previous model development to over 85% balanced accuracy. Expect model to be implemented in Westmark business practices.

`September 2027 - April 2028`
__Good2Go__, Consultant

- Built product ordering and supply predictive algorithms for chips and beverages categories
- Established standardized SQL calls and connections for PowerBI dashboards
- Found over $35k in waste and saved over 200 annual hours of store quality control work 




## Service and Work History

`2019-2020`
__Math Tutor__, BYUI

`2020-2021`
__lead at Byui Crossroads__, BYUI

`2017-2019`
__Service Missionary__, India



<!-- ### Footer

Last updated: May 2013 -->


